FROM node:14-alpine

WORKDIR /app

# this command will override, addings command after the image name when you run it.
# CMD ["abd"]

# this will append end of the image name (run command)
ENTRYPOINT ["npm"]