# match expression is more powerful than match labels

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 5
  selector:
    # matchLabels:
    #   app: second-app
    #   tier: backend
    matchExpressions:
      - key: app
        operator: In
        values:
          - second-app
      - key: tier
        operator: In
        values:
          - backend
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec: # configures the pod
      containers:
        - name: second-node-js
          image: angajasinghe/kub-first-app:2
          livenessProbe: # probe to check if the pod is alive
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: "0.2"


