apiVersion: v1
kind: Service
metadata:
  name: backend
spec: # this will control all pods that has the label app=second-app
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer