apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # only one access mode is allowed
  hostPath:
    path: /tmp/host-pv
    type: DirectoryOrCreate